### ISSUE TITLE
BLACK CAMERA on iOS - Stopped working

### ISSUE THREAD

**Issue by Guttz** [cozmo/jsQR#133] opened 2019-04-03 07:47 UTC
One week ago I've tested the repo and the demo on different devices and all of them were working. Today all of a suudden, the iOS devices I have access to, get a black camera when accessing the camera. 

All the other devices seem to work fine, do we have a workaround for this?

**Comment by kousu** [comment] 2019-04-04 07:01
This sounds like a permissions problem. Did you get an update this week?

Can you wipe any of those devices? Maybe there's a cookie or localstorage cached that's messing with things.

**Comment by Guttz** [comment] 2019-04-04 10:10
I've tried opening the demo https://cozmo.github.io/jsQR/ with icognito mode to make sure it isn't a cookie problem.  It happened on a iPhone X and iPhone 7 at the same time. 

The demo https://cozmo.github.io/jsQR/ basically shows a black screen on safari and a "loading camera" forever on chrome. 

That's actually a problem with accessing the camera with iOS but I guess there isn't a better place to comment this issue?

**Comment by TheAlexandru** [comment] 2019-05-01 08:26
on iPhone 6  works, camera opens, **but** it is very slow, about 4 fps :D 
any ideas ?

**Comment by YouriHugoBos** [comment] 2019-05-08 10:31
I have had some problems with iOS, i use zebracrossing and jsqr parallel. This is how my video element looks:  `<video className={classes.scanner} playsInline autoPlay muted ref={this.videoRef} />` Maybe you can try the playsInline, autoPlay and muted attributes @Guttz. You also need to set the contraints for the getUserMedia to `video: { facingmode: 'environment' }`. 

For the lagg on iOS @TheAlexandru i added a timeout of 300ms to the recursive `frameRequestCallback` function call, this helped some framerate, but not ideal since it now only scans every 0.3 seconds. I hope this helps out a bit...

**Comment by cozmo** [comment] 2019-06-16 17:42
A few thoughts
- Chrome will never work on iOS - iOS blocks access to `getUserMedia` inside of webviews, which is what chrome uses. 
- @TheAlexandru for performance I'd make sure to benchmark rendering video to canvas without jsQR, since jsQR can eat up a fair number of resources. If the FPS looks better there you may want to try running jsQR in a separate thread via webworkers, and potentially downscaling the video first. The tradeoffs of these solutions would have the evaluated on a case by case basis.
- As for the original black screen issue - I can't reproduce this on an iPhone running the iOS 12.3.1, which is all I have access to. I _can_ reproduce this by disabling access to the camera by clicking the camera control button in safari. Might be a good place to start
![IMG_1547](https://user-images.githubusercontent.com/696340/59567484-5940e580-9066-11e9-911f-b46e10ff3b95.jpg)

However as mentioned in the [README](https://github.com/cozmo/jsQR#a-note-on-webcams) jsQR is designed to have no webcam specific implementation details. Rather the API is designed to take in image data and output any QR codes found within. Handling reading image data from the webcam and passing it to jsQR is the responsibility of the consumer, and as such I can't provide much additional help here and am going to close the issue since it's not a jsQR issue I do not believe. Please comment/re-open if you disagree.

**Closed by cozmo** 2019-06-16 17:42 UTC
