### ISSUE TITLE
Can't use phone camera 

### ISSUE THREAD

**Issue by Clemenshemmerling** [cozmo/jsQR#74] opened 2018-07-10 22:15 UTC
Hello I try to use you demo, in pc its works but in mobile phone not detect the camara.
`var video = document.createElement("video");
var canvasElement = document.getElementById("canvas");
var canvas = canvasElement.getContext("2d");
var loadingMessage = document.getElementById("loadingMessage");
var outputContainer = document.getElementById("output");
var outputMessage = document.getElementById("outputMessage");
var outputData = document.getElementById("outputData");

function drawLine(begin, end, color) {
  canvas.beginPath();
  canvas.moveTo(begin.x, begin.y);
  canvas.lineTo(end.x, end.y);
  canvas.lineWidth = 4;
  canvas.strokeStyle = color;
  canvas.stroke();
}

// Use facingMode: environment to attemt to get the front camera on phones
navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } }).then(function(stream) {
  video.srcObject = stream;
  video.setAttribute("playsinline", true); // required to tell iOS safari we don't want fullscreen
  video.play();
  requestAnimationFrame(tick);
});

function tick() {
  loadingMessage.innerText = "⌛ Loading video..."
  if (video.readyState === video.HAVE_ENOUGH_DATA) {
    loadingMessage.hidden = true;
    canvasElement.hidden = false;
    outputContainer.hidden = false;

    canvasElement.height = video.videoHeight;
    canvasElement.width = video.videoWidth;
    canvas.drawImage(video, 0, 0, canvasElement.width, canvasElement.height);
    var imageData = canvas.getImageData(0, 0, canvasElement.width, canvasElement.height);
    var code = jsQR(imageData.data, imageData.width, imageData.height);
    if (code) {
      drawLine(code.location.topLeftCorner, code.location.topRightCorner, "#FF3B58");
      drawLine(code.location.topRightCorner, code.location.bottomRightCorner, "#FF3B58");
      drawLine(code.location.bottomRightCorner, code.location.bottomLeftCorner, "#FF3B58");
      drawLine(code.location.bottomLeftCorner, code.location.topLeftCorner, "#FF3B58");
      outputMessage.hidden = true;
      outputData.parentElement.hidden = false;
      outputData.innerText = code.data;
    } else {
      outputMessage.hidden = false;
      outputData.parentElement.hidden = true;
    }
  }
  requestAnimationFrame(tick);
}
`

**Comment by cozmo** [comment] 2018-07-10 22:58
Please read our [note on webcams](https://github.com/cozmo/jsQR#a-note-on-webcams). Specifically, jsQR isn't designed to require anything to do with webcams. All it needs is image data and doesn't care where you get it from. If you need help getting image data from a phone camera I'd turn to [webrtc](https://github.com/webrtc/samples), stackoverflow, [blogs](http://blog.teamtreehouse.com/accessing-the-device-camera-with-getusermedia), [docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia), or wherever else you normally go when learning a new API etc. 

For what it's worth I've confirmed that the example code works both on latest iOS and Android. What model phone are you using and what version is the OS? 

I'm going to close this issue because as far as I can tell it's reporting that our example code isn't cross platform, and not about an specific issue with jqQR. Please feel free to comment/re-open if you disagree.

**Closed by cozmo** 2018-07-10 22:58 UTC
